// export const FETCH_API_LIST_PRODUCT = "FETCH_API_LIST_PRODUCT";
// export const CHANGE_GENDER_TYPEPRODUCT = "CHANGE_GENDER_TYPEPRODUCT";
// export const IS_LOADING_LIST_PRODUCT = "IS_LOADING_LIST_PRODUCT";
